### ISSUE TITLE
Choose license

### ISSUE THREAD

**Issue by damianooldoni** [riparias/riparias-target-list#1]
Which license should we assign to this checklist? Is http://creativecommons.org/publicdomain/zero/1.0/ provided as example in the checklist-recipe correct for us? I think so.

**Comment by peterdesmet** [comment]
Yes, especially if we are the rightsholder (see #2), we can opt for CC0. I would write it with https (not consistently done for all datasets, but it redirects as such):

    https://creativecommons.org/publicdomain/zero/1.0/
