### ISSUE TITLE
Add project ID to metadata

### ISSUE THREAD

**Issue by damianooldoni** [riparias/riparias-target-list#20]
As we were not allowed to make a network RIPARIAS, I suggest to add `Project ID`: `LIFE19 NAT/BE/000953` to metadata.

**Comment by peterdesmet** [comment]
I would suggest the shorter and more recognizable `LIFE RIPARIAS`

**Comment by damianooldoni** [comment]
@LienReyserhove; could you please add the project page as you did for the other LFIE RIPARIAS datasets? See [Google docs](https://docs.google.com/document/d/1SyZmiLcpFJ2AcDaDFZfnqrndwQFaUcxr3eKHy3fJKQY/edit#). Thanks.

**Comment by LienReyserhove** [comment]
Done!
