### ISSUE TITLE
Update list on GBIF 

### ISSUE THREAD

**Issue by damianooldoni** [riparias/riparias-target-list#24]
I had to add the authorship to _Zizania latifolia_  (see commit d61bea7bccc4b289b7c27a6819593be295c8c8e0) to avoid a wrong match to GBIF Backbone (see https://github.com/gbif/portal-feedback/issues/4718).

Republication on IPT is needed: https://ipt.inbo.be/resource?r=riparias-target-list

**Comment by LienReyserhove** [comment]
Done!

**Comment by damianooldoni** [comment]
Thanks Lien! Zizania latifolia is matched correctly now.

**Comment by damianooldoni** [comment]
Sorry @LienReyserhove: I have to ask you to republish again this checklist. I found and solved #25.

**Comment by LienReyserhove** [comment]
republished!

**Comment by damianooldoni** [comment]
Thanks.
