### ISSUE TITLE
Choose datasetName

### ISSUE THREAD

**Issue by damianooldoni** [riparias/riparias-target-list#3]
Which `datasetName` should we choose for this list of taxa? This is the title as it will appear on GBIF. 

My proposal: _Checklist of LIFE RIPARIAS target species_

**Comment by timadriaens** [comment]
seems very appropriate, yes (I take it this excludes the alert list then)

**Comment by peterdesmet** [comment]
Or `Target species list for LIFE RIPARIAS`

**Comment by peterdesmet** [comment]
I see `Checklist of LIFE RIPARIAS target species` was adopted in script.
