### ISSUE TITLE
Define list of authors

### ISSUE THREAD

**Issue by damianooldoni** [riparias/riparias-target-list#4]
People involved in the project proposal and people involved in the alert list (Action A.1.4 I think it is)

**Comment by damianooldoni** [comment]
Authors of the alert list here below included in the same order as it appears in the deliverable:

Name | ORCID
--- | ---
Etienne Branquart |  
Tim Adriaens | https://orcid.org/0000-0001-7268-4200
Sander Devisscher | https://orcid.org/0000-0003-2015-5731
Bram D’hondt | https://orcid.org/0000-0002-1330-1457
Luc Denys | 
Antoine Dumortier |
Adrien Latli | https://orcid.org/0000-0001-6640-5930
Jo Packet | https://orcid.org/0000-0001-5590-323X
Kevin Scheers | https://orcid.org/0000-0002-4756-4247 
Sonia Vanderhoeven | https://orcid.org/0000-0002-6298-5373
Romain Willeput |

Other people to include as responsible of the mapping to DwC

Name | ORCID
--- | ---
Damiano Oldoni | https://orcid.org/0000-0003-3445-7562
Peter Desmet | https://orcid.org/0000-0002-8442-8025

People from project proposal not included in the alert list authors we should include as well?

**Comment by timadriaens** [comment]
Indeed, it's A.1.4

_A.1.4 Drafting of Belgian alert lists of IAS
Alert lists are defined as lists of alien species not yet present or with very limited distribution that pose a
threat to biodiversity, and for which dedicated surveillance and monitoring are recommended to foster
prompt response in the case of arrival and spread (Genovesi et al 2010). These lists are essential for a
proactive response towards IAS, including both early detection and rapid response. RIPARIAS will draft alert
lists for invasive aquatic plants, riparian plants and crayfish in screening existing IAS lists from neighbouring
countries and results from European horizon scanning exercises . The chances of arrival, establishment,
spread and biodiversity impact in Belgium will be considered. Training will be provided to managers and field
workers (E.2) which will lead to increased surveillance for those species in the project area (C.1). In case alert
list species are detected they will be eradicated in the 3 river basins (C.2 and C.3) even if they are not yet
listed at EU level._

I think we should also include Xavier as representative of the lead partner and he took initiative to keep a list for the project. In terms of order, think you can just use author order of the alert list as you listed above and put Xavier and yourselves in alphabetically. 

Here are some missing ORCIDs

| **Name**  | **ORCID** |
| ------------- | ------------- |
| Luc Denys  | https://orcid.org/0000-0002-1841-6579 |
| Xavier Vermeersch | https://orcid.org/0000-0003-1752-8226 |

**Comment by damianooldoni** [comment]
This is the ordered list of authors. I used the alert list order and I added:
- Xavier Vermeersch as last author (instead of second from last) due its coordinating role  and so it earns the last position
- myself in alphabetical order
- Peter Desmet almots alphabetically (as last one of the authors starting with a D to avoid putting him before Sander, Bram and Luc, who delivered important work for the list

Name | ORCID
--- | ---
Etienne Branquart |  
Tim Adriaens | https://orcid.org/0000-0001-7268-4200
Sander Devisscher | https://orcid.org/0000-0003-2015-5731
Bram D’hondt | https://orcid.org/0000-0002-1330-1457
Luc Denys  | https://orcid.org/0000-0002-1841-6579 |
Peter Desmet | https://orcid.org/0000-0002-8442-8025
Antoine Dumortier |
Adrien Latli | https://orcid.org/0000-0001-6640-5930
Damiano Oldoni | https://orcid.org/0000-0003-3445-7562
Jo Packet | https://orcid.org/0000-0001-5590-323X
Kevin Scheers | https://orcid.org/0000-0002-4756-4247 
Sonia Vanderhoeven | https://orcid.org/0000-0002-6298-5373
Romain Willeput |
Xavier Vermeersch | https://orcid.org/0000-0003-1752-8226 |

@timadriaens, please let me know if you prefer to change it.

**Comment by timadriaens** [comment]
I'd say we stay as close as possible to the citation of the alert list report because this better reflects people's input and we put the extra people in alphabetically between first and last author.

> Branquart E., Adriaens T., Devisscher S., D’hondt B., Denys L., Dumortier A., Latli A., Packet J., Scheers K., Vanderhoeven S. & Willeput R. (2021) Belgian alert lists of alien aquatic plants and crayfish. Report prepared in support of implementing action A1 of the LIFE RIPARIAS project LIFE19 NAT/BE/000953, 15 pages.

**Comment by damianooldoni** [comment]
Thanks @timadriaens. Here the list authors as you want:

Name | ORCID
--- | ---
Etienne Branquart |  
Tim Adriaens | https://orcid.org/0000-0001-7268-4200
Peter Desmet | https://orcid.org/0000-0002-8442-8025
Sander Devisscher | https://orcid.org/0000-0003-2015-5731
Bram D’hondt | https://orcid.org/0000-0002-1330-1457
Luc Denys  | https://orcid.org/0000-0002-1841-6579 |
Antoine Dumortier |
Adrien Latli | https://orcid.org/0000-0001-6640-5930
Damiano Oldoni | https://orcid.org/0000-0003-3445-7562
Jo Packet | https://orcid.org/0000-0001-5590-323X
Kevin Scheers | https://orcid.org/0000-0002-4756-4247 
Sonia Vanderhoeven | https://orcid.org/0000-0002-6298-5373
Xavier Vermeersch | https://orcid.org/0000-0003-1752-8226 |
Romain Willeput |
