### ISSUE TITLE
Write metadata

### ISSUE THREAD

**Issue by damianooldoni** [riparias/riparias-target-list#9]
@timadriaens, as we briefly discussed today, could you give a try to write the metadata for the RIPARIAS target list? I put a copy of the gdoc template in RIPARIAS/Action A1/data publicatie/RIPARIAS target list directory on gdrive. This is the link to the metadata gdoc: https://docs.google.com/document/d/1LMJyovw7Dw-snibDycEhRNfChk2R9yjFMoetdEPA2KY/edit#heading=h.m2h9y35m3fn4
Thanks.

**Comment by timadriaens** [comment]
more or less done with it, needs a check for the step description

**Comment by damianooldoni** [comment]
Thanks @timadriaens. I reviewed it. @peterdesmet, can you review further and in case proceed with the publication? Notice the two versions of the logo I added  at the end of the gdoc. These logos are project logos. I think we need to upload the project LIFE RIPARIAS to GBIF first before publishing the checklist?

**Comment by peterdesmet** [comment]
Document reviewed, actions needed. No worries about the logo, that will be arranged.

**Comment by peterdesmet** [comment]
Will look like this:

<img width="956" alt="Screenshot 2022-03-15 at 09 48 51" src="https://user-images.githubusercontent.com/600993/158340678-7d6accaa-6cd3-44e8-bc53-f9a827e7093f.png">

**Comment by timadriaens** [comment]
I think a community page is a good idea, even though we'll probably have less datasets/checklists published than for TrIAS for instance, it is good for visibility. Do you need a picture for that page? We could use the drone image they use on many comms materials.

![image](https://user-images.githubusercontent.com/16116743/158353665-78ad061c-67f2-4c47-a5dd-ff8509176677.png)

**Comment by timadriaens** [comment]
@peterdesmet credits of this photo: ©AdrienLatli, I will upload the pic here

![Drone 1](https://user-images.githubusercontent.com/16116743/158768619-04608a24-e613-4d55-ac9e-1cdbf62c1128.jpg)

**Comment by damianooldoni** [comment]
@peterdesmet: I think we are ready to publish this checklist, right? Do we need something more to close this issues? I don't think so.

**Comment by peterdesmet** [comment]
Yes, the network is not blocking the publication of the checklist. Just good if someone follows up the progress on the network submission to GBIF.

**Comment by damianooldoni** [comment]
I am following it up. Sent the document to Florence (BE) for a final review. Mail sent with you @peterdesmet in cc as well. I hope review follows fast.

**Comment by damianooldoni** [comment]
Update: the [network page text](https://docs.google.com/document/d/1SyZmiLcpFJ2AcDaDFZfnqrndwQFaUcxr3eKHy3fJKQY/edit#) has been reviewed by BE. So, we can proceed to create the network on GBIF as well.

**Comment by damianooldoni** [comment]
GBIF seems not intentioned to promote the use of networks for (temporary) projects. Networks should be a collaborations among institutes maintained over a long period of time. As LIFE RIPARIAS has a start and an end date, we should work by ifllling in project details in the metadata of each published dataset.
